# Utilizza un'immagine Node.js
FROM node:14

# Crea una directory di lavoro
WORKDIR /app

# Copia i file package.json e package-lock.json nella directory di lavoro
COPY dmn/package*.json ./

# Esegui l'installazione dei moduli Node.js
#RUN npm install
# Copia la cartella node_modules personalizzata nella directory di lavoro
COPY dmn/node_modules/ ./node_modules/


# Copia il resto del codice sorgente dell'applicazione nella directory di lavoro
COPY dmn .

# Espone la porta 5100
EXPOSE 5100

# Avvia l'applicazione utilizzando il comando 'npm start'
CMD ["npm", "start"]

